# Generated by Django 5.1.4 on 2025-02-12 18:07

import django.db.models.deletion
import logsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpHaveCar', models.BooleanField(default=False)),
                ('ceoNumber', models.CharField(default='0', max_length=100, unique=True)),
                ('ceoName', models.CharField(default='الاسم', max_length=100)),
                ('phoneNumber', models.CharField(default='0000000000', max_length=100)),


                ('email', models.EmailField(default='example@example.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RegistredCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carYear', models.IntegerField(null=True)),
                ('cownerEmpNumber', models.CharField(max_length=100, null=True)),
                ('cownerName', models.CharField(max_length=100, null=True)),
                ('cownerPhone', models.CharField(max_length=100, null=True)),
                ('section', models.CharField(max_length=100, null=True)),
                ('carNumber', models.CharField(default='0', max_length=100)),
                ('vType', models.CharField(max_length=100, null=True)),
                ('carIsInparking', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogsC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carIsInUse', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taken_date', models.DateField(blank=True, null=True)),
                ('taken_time', models.TimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('carNote', models.TextField(blank=True, null=True)),
                ('Logs_employee_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logsApp.employesinfo')),
                ('Logs_car_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logsApp.registredcars')),
            ],
        ),
        migrations.CreateModel(
            name='InUseCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logsApp.employesinfo')),
                ('logsc_ley', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logsApp.logsc')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logsApp.registredcars')),
            ],
        ),
        migrations.AddIndex(
            model_name='logsc',
            index=models.Index(fields=['Logs_employee_ins', 'carIsInUse'], name='logsApp_log_Logs_em_1a66d2_idx'),
        ),
        migrations.AddIndex(
            model_name='logsc',
            index=models.Index(fields=['Logs_car_ins', 'carIsInUse'], name='logsApp_log_Logs_ca_ec6033_idx'),
        ),
        migrations.AddIndex(
            model_name='logsc',
            index=models.Index(fields=['created_at'], name='logsApp_log_created_d07337_idx'),
        ),
        migrations.AddIndex(
            model_name='logsc',
            index=models.Index(fields=['ended_at'], name='logsApp_log_ended_a_476991_idx'),
        ),
    ]
