# Generated by Django 5.1.1 on 2024-09-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceoNumber', models.IntegerField(default=0)),
                ('ceoName', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField(default='0000000000')),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InUseCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceoNumber', models.IntegerField(default=0)),
                ('carNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegistredCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNumber', models.IntegerField(default=0)),
                ('carName', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
