# Generated by Django 5.1.4 on 2025-02-27 10:39

import django.db.models.deletion
import logsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employesinfo',
            name='department',
            field=models.CharField(default='الشعبه', max_length=100),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='jobTtile',
            field=models.CharField(default='المسمى الوظيفي', max_length=100),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='nationality',
            field=models.CharField(default='الجنسيه', max_length=100),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='unit',
            field=models.CharField(default='الوحده', max_length=100),
        ),
        migrations.AddField(
            model_name='inusecars',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inusecars',
            name='create_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccidentsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('fixin_date', models.DateField(blank=True, null=True)),
                ('report_pdf_file', models.FileField(blank=True, max_length=500, null=True, upload_to=logsApp.models.fines_accident_pdf_upload_to)),
                ('car_paperwork_file', models.FileField(blank=True, max_length=500, null=True, upload_to=logsApp.models.fines_accident_pdf_upload_to)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='logsApp.registredcars')),
                ('employees', models.ManyToManyField(blank=True, to='logsApp.employesinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FinesAccidentsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to=logsApp.models.fines_accident_file_upload_to)),
                ('accidents_record', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logsApp.accidentsrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FinesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('paidDate', models.DateField(blank=True, null=True)),
                ('paid_fine_image', models.FileField(blank=True, max_length=500, null=True, upload_to=logsApp.models.paid_fine_image_upload_to)),
                ('fine_date', models.DateField(blank=True, null=True)),
                ('fine_time', models.TimeField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='logsApp.registredcars')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logsApp.employesinfo')),
            ],
        ),
        migrations.CreateModel(
            name='GivenCarsToOtherAdminstrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherAdminstration', models.CharField(max_length=100)),
                ('empNumber', models.CharField(max_length=100)),
                ('empName', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('carIsInUse', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('taken_date', models.DateField(blank=True, null=True)),
                ('taken_time', models.TimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('retern_time', models.TimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_cars', to='logsApp.registredcars')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to=logsApp.models.fines_accident_file_upload_to)),
                ('accidents_record', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='license_files', to='logsApp.accidentsrecord')),
            ],
        ),
    ]
