# Generated by Django 5.1.4 on 2025-02-09 08:11

import logsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentsrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='accidentsrecord',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='EmpHaveCar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='ceoName',
            field=models.CharField(default='الاسم', max_length=100),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='ceoNumber',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='finesaccidentsimage',
            name='image',
            field=models.ImageField(default=None, upload_to=logsApp.models.fines_accident_file_upload_to),
        ),
        migrations.AddField(
            model_name='finesrecord',
            name='fine_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finesrecord',
            name='fine_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finesrecord',
            name='paid_fine_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=logsApp.models.paid_fine_image_upload_to),
        ),
        migrations.AddField(
            model_name='inusecars',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inusecars',
            name='create_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inusecars',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='licensefile',
            name='file',
            field=models.FileField(default=1, upload_to=logsApp.models.fines_accident_file_upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logsc',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logsc',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logsc',
            name='taken_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registredcars',
            name='cownerEmpNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registredcars',
            name='cownerName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
