# Generated by Django 5.1.4 on 2025-02-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inusecars',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
