# Generated by Django 5.1.4 on 2025-05-25 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingaragecars',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logsApp.registredcars'),
        ),
        migrations.AlterField(
            model_name='ingaragecars',
            name='maintance_emp_send_to_garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_maintenances2', to='logsApp.employesinfo'),
        ),
        migrations.AlterField(
            model_name='ingaragecars',
            name='maintance_emp_send_to_garage_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingaragecars',
            name='maintance_emp_send_to_garage_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ingaragecars',
            name='maintance_emp_send_to_garage_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
