# Generated by Django 5.1.4 on 2025-02-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employesinfo',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employesinfo',
            name='section',
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='department',
            field=models.CharField(default='الشعبه', max_length=100),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='jobTtile',
            field=models.CharField(default='المسمى الوظيفي', max_length=100),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='nationality',
            field=models.CharField(default='الجنسيه', max_length=100),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='unit',
            field=models.CharField(default='الوحده', max_length=100),
        ),
    ]
