# Generated by Django 5.1.4 on 2025-02-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0002_inusecars_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inusecars',
            name='create_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
