# Generated by Django 5.1.4 on 2025-02-02 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0002_remove_employesinfo_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenCarsToOtherAdminstrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherAdminstration', models.CharField(max_length=100)),
                ('empNumber', models.CharField(max_length=100)),
                ('empName', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('carIsInUse', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('taken_date', models.DateField(blank=True, null=True)),
                ('taken_time', models.TimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('retern_time', models.TimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logsApp.registredcars')),
            ],
        ),
    ]
