# Generated by Django 5.1.4 on 2025-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0002_employesinfo_department_employesinfo_jobttile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finesrecord',
            name='unRegistredEmpCeoNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finesrecord',
            name='unRegistredEmpName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
