# Generated by Django 5.1.4 on 2025-05-25 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0002_alter_ingaragecars_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintancelogs',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logsApp.registredcars'),
        ),
        migrations.AlterField(
            model_name='maintancelogs',
            name='maintance_emp_return_from_garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_maintenances', to='logsApp.employesinfo'),
        ),
        migrations.AlterField(
            model_name='maintancelogs',
            name='maintance_emp_return_from_garage_arriving_time_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintancelogs',
            name='maintance_emp_send_to_garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_maintenances', to='logsApp.employesinfo'),
        ),
        migrations.AlterField(
            model_name='maintancelogs',
            name='maintance_emp_send_to_garage_arriving_time_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintancelogs',
            name='maintance_emp_send_to_garage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintancelogs',
            name='maintance_emp_send_to_garage_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='maintancelogs',
            name='maintance_emp_send_to_garage_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
