# Generated by Django 5.1.1 on 2024-09-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0003_inusecars'),
    ]

    operations = [
        migrations.AddField(
            model_name='inusecars',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inusecars',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LogsC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Logs_car_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logsApp.registredcars')),
                ('Logs_employee_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logsApp.employesinfo')),
            ],
        ),
    ]
