# Generated by Django 5.1.4 on 2025-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0003_givencarstootheradminstrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givencarstootheradminstrations',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
