# Generated by Django 5.1.4 on 2025-02-12 18:23

import django.db.models.deletion
import logsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0004_employesinfo_department_employesinfo_jobttile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('fixin_date', models.DateField(blank=True, null=True)),
                ('report_pdf_file', models.FileField(blank=True, max_length=500, null=True, upload_to=logsApp.models.fines_accident_pdf_upload_to)),
                ('car_paperwork_file', models.FileField(blank=True, max_length=500, null=True, upload_to=logsApp.models.fines_accident_pdf_upload_to)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='logsApp.registredcars')),
                ('employees', models.ManyToManyField(blank=True, to='logsApp.employesinfo')),
            ],
        ),
    ]
