# Generated by Django 5.1.1 on 2024-09-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0004_inusecars_created_at_alter_inusecars_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsc',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
