# Generated by Django 5.0.4 on 2024-09-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0005_logsc_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registredcars',
            name='carCode',
            field=models.IntegerField(default=0),
        ),
    ]
