# Generated by Django 5.0.4 on 2024-09-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0006_registredcars_carcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='inusecars',
            name='logsc_ley',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logsApp.logsc'),
        ),
    ]
