# Generated by Django 5.1.4 on 2025-02-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0006_finesaccidentsimage_finesrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finesrecord',
            name='unRegistredEmp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
