# Generated by Django 5.1.4 on 2025-02-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0007_finesrecord_unregistredemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finesrecord',
            old_name='unRegistredEmp',
            new_name='unRegistredEmpCeoNumber',
        ),
        migrations.AddField(
            model_name='finesrecord',
            name='unRegistredEmpName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
