# Generated by Django 5.0.4 on 2024-09-11 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0007_inusecars_logsc_ley'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsc',
            name='inusecarin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logsApp.inusecars'),
        ),
    ]
