# Generated by Django 5.1.2 on 2025-01-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0007_alter_finesrecord_paid_fine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='finesrecord',
            name='fine_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finesrecord',
            name='fine_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
