# Generated by Django 5.1.2 on 2025-01-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0008_finesrecord_fine_date_finesrecord_fine_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='finesrecord',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
