# Generated by Django 5.1.4 on 2025-01-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0009_finesrecord_fine_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registredcars',
            name='carNumber',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='registredcars',
            name='cownerEmpNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registredcars',
            name='cownerName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registredcars',
            name='cownerPhone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registredcars',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registredcars',
            name='vType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
