# Generated by Django 5.0.4 on 2024-09-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0009_logsc_carisinuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='employesinfo',
            name='EmpHaveCar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registredcars',
            name='carIsInparking',
            field=models.BooleanField(default=True),
        ),
    ]
