# Generated by Django 5.1.4 on 2025-02-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0010_alter_registredcars_carnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inusecars',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inusecars',
            name='create_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
