# Generated by Django 5.0.4 on 2024-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0011_remove_logsc_inusecarin_logsc_carnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsc',
            name='dateFilter',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
