# Generated by Django 5.0.4 on 2024-09-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0013_alter_logsc_carnote_alter_logsc_datefilter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registredcars',
            old_name='carName',
            new_name='vType',
        ),
        migrations.RemoveField(
            model_name='registredcars',
            name='carCode',
        ),
        migrations.AddField(
            model_name='registredcars',
            name='carYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registredcars',
            name='cownerEmpNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registredcars',
            name='cownerName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registredcars',
            name='cownerPhone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registredcars',
            name='section',
            field=models.TextField(null=True),
        ),
    ]
