# Generated by Django 5.1.1 on 2024-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0015_employesinfo_position_employesinfo_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employesinfo',
            name='ceoNumber',
            field=models.TextField(default=0),
        ),
    ]
