# Generated by Django 5.1.1 on 2024-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0016_alter_employesinfo_ceonumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logsc',
            old_name='dateFilter',
            new_name='return_date',
        ),
        migrations.AddField(
            model_name='logsc',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logsc',
            name='taken_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='logsc',
            name='taken_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
