# Generated by Django 5.1.1 on 2024-09-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0017_rename_datefilter_logsc_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logsc',
            name='taken_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='logsc',
            name='taken_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
