# Generated by Django 5.1.1 on 2024-09-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0018_alter_logsc_created_at_alter_logsc_taken_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employesinfo',
            name='ceoNumber',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employesinfo',
            name='phoneNumber',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='employesinfo',
            name='position',
            field=models.CharField(default='الوظيفه', max_length=100),
        ),
        migrations.AlterField(
            model_name='employesinfo',
            name='section',
            field=models.CharField(default='القسم', max_length=100),
        ),
    ]
