# Generated by Django 5.1.1 on 2024-09-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0019_alter_employesinfo_ceonumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employesinfo',
            name='ceoNumber',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
