# Generated by Django 5.1.1 on 2024-11-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0020_alter_employesinfo_ceonumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
