# Generated by Django 5.1.2 on 2024-11-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0020_alter_employesinfo_ceonumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinesAccidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
