# Generated by Django 5.1.1 on 2024-11-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0021_finesaccidents'),
        ('logsApp', '0021_imgtest'),
    ]

    operations = [
    ]
