# Generated by Django 5.1.1 on 2024-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0022_merge_0021_finesaccidents_0021_imgtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imgtest',
        ),
        migrations.AddField(
            model_name='finesaccidents',
            name='text',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
