# Generated by Django 5.1.2 on 2024-12-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0023_delete_imgtest_finesaccidents_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='finesaccidents',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logsApp.registredcars'),
        ),
        migrations.AddField(
            model_name='finesaccidents',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logsApp.employesinfo'),
        ),
        migrations.AddField(
            model_name='finesaccidents',
            name='event_regestred_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='FinesAccidentsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('fines_accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logsApp.finesaccidents')),
            ],
        ),
    ]
