# Generated by Django 5.1.2 on 2024-12-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0024_finesaccidents_car_finesaccidents_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finesaccidents',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='finesaccidents',
            name='event_regestred_at',
        ),
        migrations.RemoveField(
            model_name='finesaccidents',
            name='image',
        ),
        migrations.AddField(
            model_name='finesaccidents',
            name='employees',
            field=models.ManyToManyField(blank=True, to='logsApp.employesinfo'),
        ),
        migrations.AlterField(
            model_name='employesinfo',
            name='ceoNumber',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='finesaccidents',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logsc',
            name='carNote',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registredcars',
            name='carNumber',
            field=models.TextField(default='0'),
        ),
    ]
