# Generated by Django 5.1.2 on 2024-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0025_remove_finesaccidents_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finesaccidents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
