# Generated by Django 5.1.2 on 2024-12-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0026_finesaccidents_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='finesaccidents',
            name='fixin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finesaccidents',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finesaccidents',
            name='report_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
