# Generated by Django 5.1.2 on 2024-12-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0027_finesaccidents_fixin_date_finesaccidents_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finesaccidents',
            name='report_pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='logsc',
            name='carNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logsc',
            name='taken_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logsc',
            name='taken_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='logsc',
            index=models.Index(fields=['Logs_employee_ins', 'carIsInUse'], name='logsApp_log_Logs_em_1a66d2_idx'),
        ),
        migrations.AddIndex(
            model_name='logsc',
            index=models.Index(fields=['Logs_car_ins', 'carIsInUse'], name='logsApp_log_Logs_ca_ec6033_idx'),
        ),
        migrations.AddIndex(
            model_name='logsc',
            index=models.Index(fields=['created_at'], name='logsApp_log_created_d07337_idx'),
        ),
        migrations.AddIndex(
            model_name='logsc',
            index=models.Index(fields=['ended_at'], name='logsApp_log_ended_a_476991_idx'),
        ),
    ]
